# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: 'Every Push'

on: push

jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v3

      - name: 'Setup Node.js'
        uses: actions/setup-node@v3
        with:
          node-version: ${{ secrets.NODE_VERSION }}

      - name: 'Cache node modules'
        uses: actions/cache@v3
        id: cache
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/yarn.lock') }}

      - name: 'Install dependencies'
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn install

      - run: yarn lint
        if: ${{ always() }}
      - run: yarn build
        if: ${{ always() }}
