# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: 'Npm Publish'

on:
  release:
    types: [created]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v3

      - name: 'Setup Node.js'
        uses: actions/setup-node@v3
        with:
          node-version: ${{ secrets.NODE_VERSION }}
          registry-url: https://registry.npmjs.org/

      - name: 'Cache node modules'
        uses: actions/cache@v3
        id: cache
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/yarn.lock') }}

      - name: 'Install dependencies'
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn install

      - name: 'Build package'
        run: yarn build

      - name: 'Publish package'
        run: yarn pkgs:publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
